[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-L", "native=/Users/devarajns/Library/Caches/cargo-xwin/xwin/crt/lib/x86_64",
  "-L", "native=/Users/devarajns/Library/Caches/cargo-xwin/xwin/sdk/lib/ucrt/x86_64",
  "-L", "native=/Users/devarajns/Library/Caches/cargo-xwin/xwin/sdk/lib/um/x86_64"
]
